stages:
  - maven-build
  - android-build
  - maven-test
  - android-test
  - maven-deploy
  - android-deploy

variables:
  APP_VERSION: 1
  APP_NAME: backend
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -f Backend/backend/pom.xml
    -DinstallAtEnd=true
    -DdeployAtEnd=true

###### BUILD JOBS ######

build-spring-dev:
  # rules:
    # - if: $CI_COMMIT_BRANCH == "backend-dev"
  tags:
    - springboot_tag
  stage: maven-build
  script:
    - mvn $MAVEN_CLI_OPTS verify
    - cp Backend/backend/target/$APP_NAME-$APP_VERSION.jar /home/gitlab-runner/build/temp/

build-spring-main:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - springboot_tag
  stage: maven-build
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $SSH_PORT $SSH_ADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - mvn $MAVEN_CLI_OPTS verify
    - scp -o StrictHostKeyChecking=no -P $SSH_PORT /home/gitlab-runner/release/$APP_NAME-$APP_VERSION.jar $SSH_USER@$SSH_ADDRESS:/home/gitlab-runner/temp/$APP_NAME-$APP_VERSION.jar
    - cp Backend/backend/target/$APP_NAME-$APP_VERSION.jar /home/gitlab-runner/release/temp/
  # artifacts:
  #   paths:
  #     - Backend/backend/target/*.jar

build-android:
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "frontend-dev"
  tags:
    - android_tag
  stage: android-build
  script:
    - echo "STUB!"

###### TEST JOBS ######

test-spring-dev:
  rules:
    - if: $CI_COMMIT_BRANCH == "backend-dev"
  tags:
    - springboot_tag
  stage: maven-test
  script:
    - echo "STUB!"

test-spring-main:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - springboot_tag
  stage: maven-test
  script:
    - echo "STUB!"

test-android-dev:
  rules:
    - if: $CI_COMMIT_BRANCH == "frontend-dev"
  tags:
    - android_tag
  stage: android-test
  script:
    - echo "STUB!"

test-android-main:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - android_tag
  stage: android-test
  script:
    - echo "STUB!"

###### DEPLOY JOBS ######

deploy-spring-dev:
  rules:
    - if: $CI_COMMIT_BRANCH == "backend-dev"
  tags:
    - springboot_tag
  stage: maven-deploy
  script:
    - sudo systemctl stop cs309.service
    - cp /home/gitlab-runner/build/temp/* /home/gitlab-runner/build/
    - rm /home/gitlab-runner/build/temp/*
    - ln -sf /home/gitlab-runner/build/$APP_NAME-$APP_VERSION.jar /home/gitlab-runner/build/latest.jar
    - sudo systemctl start cs309.service

deploy-spring-main:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - springboot_tag
  stage: maven-deploy
  script:
    - sudo systemctl stop cs309prod.service
    - cp /home/gitlab-runner/release/temp/* /home/gitlab-runner/release/
    - rm /home/gitlab-runner/release/temp/*
    - ln -sf /home/gitlab-runner/release/$APP_NAME-$APP_VERSION.jar /home/gitlab-runner/release/latest.jar
    - sudo systemctl start cs309prod.service

deploy-spring-prod:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  variables:
    GIT_STRATEGY: none
  tags:
    - deploy_tag
  stage: maven-deploy
  script:
    - sudo systemctl stop cs309.service
    - cp /home/gitlab-runner/temp/* /home/gitlab-runner/
    - rm /home/gitlab-runner/temp/*
    - ln -sf /home/gitlab-runner/$APP_NAME-$APP_VERSION.jar /home/gitlab-runner/latest.jar
    - sudo systemctl start cs309.service