stages:
  - build
  - test
  - deploy

variables:
  APP_VERSION: 1
  APP_NAME: backend
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -f Backend/backend/pom.xml
    -DinstallAtEnd=true
    -DdeployAtEnd=true

image: maven:3.8-openjdk-11

build:
  variables:
    JOB_MODE: "test"
  stage: build
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  script:
    - mvn $MAVEN_CLI_OPTS verify
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "**/target/*.jar"
    reports:
      junit:
        - "**/target/*-reports/TEST-*.xml"

deploy-prod:
  variables:
    JOB_MODE: "deploy"
  stage: deploy
  script:
    - java -jar **/target/$APP_NAME-$APP_VERSION.jar
  environment: production
